"""Add soft delete to produtos table

Revision ID: 23ef7d8eb711
Revises: 8c104f9dd94e
Create Date: 2025-11-18 14:49:38.576159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ef7d8eb711'
down_revision = '8c104f9dd94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Simplified migration - just add deleted_at column to produtos
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
    # ### end Alembic commands ###
