"""Initial migration

Revision ID: 8c104f9dd94e
Revises: 
Create Date: 2025-11-17 19:39:57.997312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c104f9dd94e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Apenas criar índices - não alterar ForeignKeys existentes no SQLite
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cupons_codigo'), ['codigo'], unique=True)

    with op.batch_alter_table('itens_carrinho', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_carrinho_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_carrinho_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('produto_visualizacoes', schema=None) as batch_op:
        batch_op.create_index('idx_produto_data', ['produto_id', 'data_visualizacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_visualizacoes_data_visualizacao'), ['data_visualizacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_visualizacoes_produto_id'), ['produto_id'], unique=False)

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_subcategoria_id'), ['subcategoria_id'], unique=False)

    with op.batch_alter_table('subcategorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subcategorias_categoria'), ['categoria'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Apenas remover índices
    with op.batch_alter_table('subcategorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcategorias_categoria'))

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_subcategoria_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_nome'))
        batch_op.drop_index(batch_op.f('ix_produtos_categoria'))

    with op.batch_alter_table('produto_visualizacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produto_visualizacoes_produto_id'))
        batch_op.drop_index(batch_op.f('ix_produto_visualizacoes_data_visualizacao'))
        batch_op.drop_index('idx_produto_data')

    with op.batch_alter_table('itens_carrinho', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_carrinho_session_id'))
        batch_op.drop_index(batch_op.f('ix_itens_carrinho_produto_id'))

    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cupons_codigo'))

    # ### end Alembic commands ###
